/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.twilio;

import org.junit.Test;

import javax.xml.transform.OutputKeys;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import java.io.StringReader;
import java.io.StringWriter;

public class TwilioTestCase {

    @Test
    public void invokeSomeMethodOnTheCloudConnector() throws Exception {
        String sid = "AC970e46372f082a4947642b9cf19cafa7";
        String authToken = "e92e7c636f007f1f2abfc39405b17a7c";

        TwilioConnector twilioCloudConnector = new TwilioConnector();
        twilioCloudConnector.setAccountSid(sid);
        twilioCloudConnector.setAuthToken(authToken);
        twilioCloudConnector.initialise();

        String response = twilioCloudConnector.getAccountDetails(null);

        printXml(response);
//
//        String subAccount = twilioCloudConnector.createSubAccount("nueva subaccountsid");
//
//        printXml(subAccount);
//
//        response = twilioCloudConnector.getAccountDetails(sid);
//
//        printXml(response);

    }

    private void printXml(String response) throws Exception {
        Source xmlInput = new StreamSource(new StringReader(response));
        StreamResult xmlOutput = new StreamResult(new StringWriter());
        Transformer transformer = TransformerFactory.newInstance().newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");
        transformer.transform(xmlInput, xmlOutput);
        System.out.println(xmlOutput.getWriter().toString());
    }
}